### ISSUE TITLE
Unable to install the package via blitz recipe

### ISSUE THREAD

**Issue by noxify** [ntgussoni/blitz-guard#74]
### What is the problem?

While running `blitz install ntgussoni/blitz-guard-recipe` I have received the following error message

```
(node:15026) UnhandledPromiseRejectionWarning: Error: At least one choice must be selectable
    at AutoComplete.reset (/Users/marcusreinhardt/Development/sla-repo/.blitz/recipe-install/node_modules/enquirer/lib/types/array.js:38:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at AutoComplete.initialize (/Users/marcusreinhardt/Development/sla-repo/.blitz/recipe-install/node_modules/enquirer/lib/types/array.js:25:5)
    at /Users/marcusreinhardt/Development/sla-repo/.blitz/recipe-install/node_modules/enquirer/lib/prompt.js:236:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15026) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to Reproduce

1. Create a new blitz app
2. (optional) In my case I have also installed tailwind as recipe
3. (optional) Added Github OAuth and configured it
4. Copy&Paste the install command
5. Run the command in the VSC Terminal
6. Confirm the following step:
```
+–––––––––––––––––––––––+
⎪   Add Ability File    ⎪
+–––––––––––––––––––––––+
One file to rule them all, this is the main file where your rules will live. Creating that for you now.

IDENTICAL app/guard/ability.ts

Press ENTER to continue
```
7. The error occurs 🙈

### Versions

```
macOS | darwin-x64 | Node: v14.16.0

blitz: 0.36.4 (global)
blitz: 0.36.4 (local)

  Package manager: yarn 
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 510.70 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.config/yarn/global/node_modules/.bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: ~2.20 => 2.20.1 
    blitz: 0.36.4 => 0.36.4 
    prisma: ~2.20 => 2.20.1 
    react: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    react-dom: 0.0.0-experimental-6a589ad71 => 0.0.0-experimental-6a589ad71 
    typescript: ~4.2 => 4.2.4 

----

macOS Big Sur | darwin-x64 | Node: v15.11.0

blitz: 0.37.0 (global)
blitz: 0.37.0 (local)

  Package manager: npm 
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 727.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.2 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.25.0 => 2.25.0 
    blitz: 0.37.0 => 0.37.0 
    prisma: 2.25.0 => 2.25.0 
    react: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    react-dom: 0.0.0-experimental-0eea57724 => 0.0.0-experimental-0eea57724 
    typescript: ~4.3.2 => 4.3.2 

```

### Other

Please include applicable logs and screenshots that show your problem.

![image](https://user-images.githubusercontent.com/521777/120872513-47341680-c59f-11eb-9f64-08f04f45b58e.png)

**Comment by ntgussoni** [comment]
This looks like it might be related to Blitz, let me do some investigations

**Comment by noxify** [comment]
Updated the initial post with the env from my second test with a fresh blitz installation ( since they have provided a new version ).

The result is, unfortunately, the same.

Current workaround ( for everyone who has the same problem ):

> **INFO**: This is only required in case you want to see unprotected routes in develop mode.

1. Open the `blitz.config.ts`
2. Add `import { BlitzGuardMiddleware } from "@blitz-guard/core/dist/middleware"` at the top of the file
3. Add the following lines to the `middleware` configuration:

```
BlitzGuardMiddleware({
  excluded: [
    "/api/auth/mutations/login",
    "/api/auth/mutations/logout",
    "/api/guard/queries/getAbility",
  ],
}),
```

----

@ntgussoni - For me, the issue has a low priority, because the important files were created, it's just the update in the `blitz.config.ts`

**Comment by ntgussoni** [comment]
Oh I get it now. The recipe expects a config.js! 
Thanks for debugging this! I'm currently on vacation away from a computer but if you find the time and you are willing to fix it I'll be more than glad to merge that pr.

**Comment by noxify** [comment]
i will give it a try ✌️

**Comment by ntgussoni** [comment]
That makes sense @noxify , we might need to change the recipe a little bit or make it more clever to deal with both situations.

**Comment by ntgussoni** [comment]
This has been addressed with the last updated
